### PR TITLE
Fix #209 Show error dialog when setup failed.

### LINKED ISSUE #209: No notification on setup errors during onboarding process
During the onboarding the setup process may end up failing on that condition from the onboarding perspective we do not get any notification. 

Actually the onboarding process seems to finish successfully so crc start should be possible directly

### PR DESCRIPTION
**Pull request by gbraad**
Fixes https://github.com/code-ready/tray-electron/issues/209

image

### CODE REVIEW

File: frontend/src/components/SetupSpinner.tsx [hunk 1]
```diff
@@ -10,6 +10,7 @@ import {
 } from '@patternfly/react-core';
 
 import "./SetupSpinner.scss";
+import LogsWindow from '../windows/LogsWindow';
```
Comment (anjannath) [inline frontend/src/components/SetupSpinner.tsx]: unused import, causing the CI failure: https://app.circleci.com/pipelines/github/code-ready/tray-electron/380/workflows/6d913c06-7f2a-4724-8f3f-b84a629bf81c/jobs/397

Comment (gbraad) [reply frontend/src/components/SetupSpinner.tsx]: hmmm... oops.

**Review by evidolob — APPROVED** [review]

**Review by anjannath — APPROVED** [review]
